POST ${process.env.NEXT_PUBLIC_API_URL}/board
content-type: application/json

{
    "articleId": "1",
    "name": "sample",
    "title":"test",
    "contents":"test",
    "writeTime": "Wed, 21 Oct 2015 18:27:50 GMT",
    "like": 0
}

###글 한개
GET ${process.env.NEXT_PUBLIC_API_URL}/board/5
content-type: application/json
